version: '3'
services:
  flavor-fiesta-db:
    image: postgres:16
    container_name: flavor-fiesta-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flavor_fiesta
      POSTGRES_DB: flavor_fiesta
      POSTGRES_PASSWORD: flavor_password
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
